### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ktalebian** [ExpediaGroup/cyclotron#91]
This project hasn't been updated in a while. Is this project still maintained?

**Comment by baumandm** [comment]
Hi @ktalebian, unfortunately this project is no longer being maintained due to changing priorities.  The tech stack has also not aged well, so at least the front-end would need a complete rewrite, which isn't something that we're currently able to undertake.

**Comment by ktalebian** [comment]
Thanks @baumandm. It would be helpful if the readme could be updated to notify everyone about the status of this project.
